### ISSUE TITLE
Make bilingual?

### ISSUE THREAD

**Issue by kadir-ince** [philhawksworth/eleventyone#27]
Hello where is the "collections"? I couldn't find.
I want to make the website bilingual like as below 👇🏼
<p align="center">
  <img src="https://i.ibb.co/hXK93nS/Screen-Shot-2020-07-11-at-13-31-20.png" style="width: 100%">
</p>

for loop is iterate in collections. I want to duplicate "site > posts" folder and create 2 .md file, one of them English one of them Turkish. I write 2 ul.listening. 
1- for page in collections.page 🇬🇧
2- for page in collections.pageTR 🇹🇷
and should show the homepage as above.

<p align="center">
  <img src="https://i.ibb.co/1dxyMF6/Screen-Shot-2020-07-11-at-13-28-34.png" style="width: 100%">
</p>

Can you help me?

**Comment by philhawksworth** [comment]
With 11ty, you can create custom collections which you can then iterate over in your templates.
Take a look at the docs for custom collection filtering. You'd be able to assemble a collection for each language based on some conventions in your filenames for example.

https://www.11ty.dev/docs/collections/#advanced-custom-filtering-and-sorting

Closing this issue since it's not an issue on this project but a search for 11ty configuration help.

More great help available on the 11ty community discord: https://www.11ty.dev/news/discord/
